### PR TITLE
ANE-380: mask ids in examples

### PR DESCRIPTION
**Pull request by tRavAsty**
First, run this command to build the docs:

```
docker run --rm --name slate -v $(pwd)/build:/srv/slate/build -v $(pwd)/source:/srv/slate/source slatedocs/slate
```

then, open `build/index.html` to view the changes.

Screen Shot 2021-08-23 at 4 42 49 PM

### CODE REVIEW

**Review by ptrckqn — APPROVED** [review]
lgtm

**Comment by hashx101** [comment]
add changelog for v1.1 release on aug 30:
Data API v1.1 release, the following are the changes available for v1.1
-chatter_id field available in messages endpoint response field
-filter by chatter_id or conversation_id for messages endpoint

Added 30 days expiration token for trial accounts.

**Comment by tRavAsty** [comment]
> add changelog for v1.1 release on aug 30:
> Data API v1.1 release, the following are the changes available for v1.1
> -chatter_id field available in messages endpoint response field
> -filter by chatter_id or conversation_id for messages endpoint
> 
> Added 30 days expiration token for trial accounts.

added above message as a html table, refs https://stackoverflow.com/questions/19950648/how-to-write-lists-inside-a-markdown-table

**Review by AdamGlustein — APPROVED** [review]
Fields are masked now

**Review by uesenthi — APPROVED** [review]
lgtm!

**Pull request merged**
